language: php
-os:
-  - linux
-dist: xenial xerus
-php:
-    - 7.0
-    - 7.1
-
-script: phpunit test.php
-
-install:
-  
-  # Install coveralls.phar
-  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
-  - chmod +x coveralls.phar
-  - php coveralls.phar --version
